import logging
from typing import Dict
from backend.models.investigation_models import PlannerOutput, InvestigatorOutput, EvidenceBundle, Evidence
from backend.tools.base_tool import BaseTool

logger = logging.getLogger(__name__)

class InvestigatorAgent:
    """
    Agent responsible for executing an investigation plan sequentially without using an LLM.
    It takes a list of tools via dependency injection and returns a structured EvidenceBundle.
    """
    
    def __init__(self, tools: Dict[str, BaseTool]):
        """
        Initialize the InvestigatorAgent with a dictionary of tools.
        
        Args:
            tools (Dict[str, BaseTool]): A mapping of tool names to initialized BaseTool instances.
        """
        self.tools = tools
        logger.info(f"InvestigatorAgent initialized with tools: {list(self.tools.keys())}")
        
    def process_plan(self, plan: PlannerOutput) -> InvestigatorOutput:
        """
        Execute the provided investigation plan and gather evidence.
        
        Args:
            plan (PlannerOutput): The plan generated by the Planner Agent.
            
        Returns:
            InvestigatorOutput: The summary of execution and the gathered EvidenceBundle.
        """
        logger.info(f"InvestigatorAgent starting to process plan: '{plan.summary}'")
        evidence_list = []
        
        for task in plan.investigation_plan:
            tool_name = task.tool
            parameters = task.parameters or {}
            logger.info(f"Executing task for tool: {tool_name} with priority: {task.priority}")
            
            tool = self.tools.get(tool_name)
            
            if not tool:
                logger.warning(f"Tool '{tool_name}' is not available in the InvestigatorAgent.")
                evidence_list.append(Evidence(
                    tool=tool_name,
                    result={},
                    success=False,
                    error=f"Tool '{tool_name}' not found."
                ))
                continue
                
            try:
                # Execute the tool
                result = tool.run(parameters)
                
                # Check if the tool itself returned an error dictionary
                if isinstance(result, dict) and "error" in result:
                    logger.warning(f"Tool '{tool_name}' executed but returned an error: {result['error']}")
                    evidence_list.append(Evidence(
                        tool=tool_name,
                        result=result,
                        success=False,
                        error=result["error"]
                    ))
                else:
                    logger.info(f"Tool '{tool_name}' executed successfully.")
                    evidence_list.append(Evidence(
                        tool=tool_name,
                        result=result,
                        success=True
                    ))
                    
            except Exception as e:
                logger.error(f"Tool '{tool_name}' raised an exception during execution: {e}")
                evidence_list.append(Evidence(
                    tool=tool_name,
                    result={},
                    success=False,
                    error=str(e)
                ))
                
        # Aggregate the evidence
        evidence_bundle = EvidenceBundle(evidence_list=evidence_list)
        
        # Prepare the final output
        summary = f"Executed {len(plan.investigation_plan)} tasks. " \
                  f"Successfully gathered evidence from {sum(1 for e in evidence_list if e.success)} tools."
                  
        logger.info("InvestigatorAgent finished processing the plan.")
        return InvestigatorOutput(
            summary=summary,
            evidence_bundle=evidence_bundle
        )
